---
title: "Croissance du sapin *Abies balsamea* (L.) Mill., 1768 au mont Moosilauke"
author: "___"
date: "`r Sys.Date()`"
lang: "fr"
bibliography: bibliography.bib
output: html_document
---

# Introduction

@wood_2015 ont étudié la croissance de *Abies balsamea*. Ils réalisent différents modèles linéaires et non linéaires et mettent en évidence que le modèle de Gompertz est le plus approprié.

# Analyses

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R("model", lang = "fr")
```

<!--% Importez les données abies.rds et ne gardez que les individus compris entre 950 et 1050m d'altitude.-->

```{r import}

```

<!--% Réalisez un graphique de la hauteur en fonction du diamètre à 1.37m du sol.-->

```{r plot}

```

<!--% Interprétez ce graphique en 3 phrase maximum-->

<!--% Modélisez la hauteur en fonction du diamètre. -->

```{r model}

```

<!--% Interprétez le résumé du modèle en 3 phrases maximum.-->

<!--% Écrivez ici le modèle paramétré, sous forme d'une équation LaTeX -->

$$ ___ $$

<!--% Réalisez un graphique de la hauteur en fonction du diamètre à 1.37m du sol. Ajoutez sur ce graphique le modèle obtenu. -->

```{r plot_model}

```

# Discussions et conclusions

<!--% Tirez des conclusions de votre étude en 3 phrases maximum. -->
